### ISSUE TITLE
Issues when swiping fast

### ISSUE THREAD

**Issue by vajahatalee** [marcosgriselli/SwipeableTabBarController#24]
When I try to swipe screen quickly, then screen is not swiping. And when I swipe slowly(touch finger over screen and swiping gently) , it works fine.
Any idea? Is there some thing I am missing?

Great Work!

**Comment by marcosgriselli** [comment]
Hey @vajahatalee thanks 😀! I believe removing restricted swipe will help you add quick swiping `setDiagonalSwipe(enabled: true)`. It comes with downsides but if you truly need fast swipe this is what's holding you back.

**Comment by alwinlazar** [comment]
@marcosgriselli Can you let me know the downsides

**Comment by marcosgriselli** [comment]
@Alwin-Lazar having diagonal swipe is really sensitive so any movement in either direction will kickstart the transition. It can be annoying if you're using any scrollview (tableView, collectionview) but otherwise the UX should be good.

**Comment by alwinlazar** [comment]
@marcosgriselli Thanks for the replay. your library is pretty good. Swipe slowly it works fine, but when I swipe fast it freeze? How to overcome this issue?

**Comment by marcosgriselli** [comment]
Thanks @Alwin-Lazar! Are you sure you are using the latest version? That issue should be fixed on the [1.1.1 release](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/1.1.1)

**Comment by alwinlazar** [comment]
@marcosgriselli the issue is still there. I am using 1.1.1 version
